name: CI (Python)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # 2) Set up Python (you can adjust the version as needed)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 3) Install dependencies
      # Make sure you have a requirements.txt (or a similar way to install your deps)
      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      # 4) Run your tests
      - name: Run tests
        run: pytest tests/
