name: CI (Python)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full history is fetched for comparison

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt && pip install black

      - name: Check Black formatting
        run: |
          # Determine the base branch for comparison
          git fetch origin $(git rev-parse --abbrev-ref HEAD) --depth=1
          BASE_BRANCH=$(git merge-base HEAD origin/main)
          # List changed .py files compared to the base branch
          CHANGED_FILES=$(git diff --name-only $BASE_BRANCH -- '*.py')
          if [ -n "$CHANGED_FILES" ]; then
            echo "$CHANGED_FILES" | xargs black --check
          else
            echo "No Python files were changed."
          fi
        shell: bash

      - name: Run tests
        run: pytest tests/